access_token = "ya29.a0Aa4xrXOj713clnSEJ7bmS0WxyJXwSToVNd47OuvCEn6GCYEHIWUXMdasdq_UEM6vdx2TnmhiTlCyc0c5fn32-mbV-aRwVga9Rsadawch2312ey6lOg8JqFIhH8APtpCcbezC3n4OWIC680CkWnozrpE-9ZXbIkL5qy05R9dp5_DXaCgYKATASARMSFQEjDvL9ATxdpvYa0vsd_xhn-95Arg0163"
client_id = "768663818257-kehq12350i7ul5brs32ej5iisl8t80nv6434drasd.apps.googleusercontent.com"
client_secret = "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OJ1gp"
refresh_token = "1//09abh74tOtNovCgYIARAAGAkSNwF-L9IrtGgmlZuigy123V1wawdaQYNn5-BoTJn-AeOFL8950fCjLlAjmsZ_QNn0zYLJaF8QSfb8D_38P0"
token_expiry = "2022-09-14T21:08:09Z"
token_uri = "https://oauth2.googleapis.com/token"
revoke_uri = "https://oauth2.googleapis.com/revoke"
scopes = [ "https://www.googleapis.com/auth/drive" ]
token_info_uri = "https://oauth2.googleapis.com/tokeninfo"
invalid = false
_class = "OAuth2Credentials"
_module = "oauth2client.client"

[token_response]
access_token = "ya29.a0Aa4xrXOj7clnSEJ7bmS0123WxyJXwSToVawdsN47aawdOuvCEn6GCYEHIWUXMq_UEM6vdx2TnmhiTlCyc0c5455fn32-mbV-aRwVga9Rchey6lOg8JqFIhH8AP231tpCger13cbezC3n4OWIC680CkWnozrpE-9ZXbIkL5qy05R9dp5_DXaCgYKATASARMSFQEjDvL9ATxdpvYa0vsd_xhn-95Arg0163"
expires_in = 3_599
refresh_token = "1//09abh74tOtNovCgYIARAAGAkSNwF-L9IrtGgmlZuigyV1wQYNn5-BoTJn-AeOFL8950fCjLlAjmsZ_QNn0zYLJaF8QSfb8D_38P0"
scope = "https://www.googleapis.com/auth/drive"
token_type = "Bearer"
